### ISSUE TITLE
config.NewFormEnv 方法命名错误

### ISSUE THREAD

**Issue by gggwvg** [longbridgeapp/openapi-go#28]
https://github.com/longbridgeapp/openapi-go/blob/5c70eec01a714e85a09e88dab98791c73660cdae/config/config.go#L52

`config.NewFormEnv` 应该是 `config.NewFromEnv`，可以改下名称吗？

**Comment by Patrick0308** [comment]
#29 这个 pr deprecated 这个方法，请使用 config.New() 创建 config
